//
//  ADIFParserTests.swift
//  CarrierWaveCoreTests
//

import Foundation
import Testing
@testable import CarrierWaveCore

@Suite("ADIF Parser Tests")
struct ADIFParserTests {
    @Test("Parse simple record")
    func parseSimpleRecord() throws {
        let adif = "<call:4>W1AW <band:3>20m <mode:2>CW <qso_date:8>20240115 <time_on:4>1430 <eor>"

        let parser = ADIFParser()
        let records = try parser.parse(adif)

        #expect(records.count == 1)
        #expect(records[0].callsign == "W1AW")
        #expect(records[0].band == "20m")
        #expect(records[0].mode == "CW")
    }

    @Test("Parse multiple records")
    func parseMultipleRecords() throws {
        let adif = """
        <call:4>W1AW <band:3>20m <mode:2>CW <qso_date:8>20240115 <time_on:4>1430 <eor>
        <call:4>K3LR <band:3>40m <mode:3>SSB <qso_date:8>20240115 <time_on:4>1445 <eor>
        """

        let parser = ADIFParser()
        let records = try parser.parse(adif)

        #expect(records.count == 2)
        #expect(records[0].callsign == "W1AW")
        #expect(records[1].callsign == "K3LR")
        #expect(records[1].mode == "SSB")
    }

    @Test("Parse with header")
    func parseWithHeader() throws {
        let adif = """
        Generated by Test App
        <adif_ver:5>3.1.4
        <programid:8>TestApp
        <eoh>
        <call:4>W1AW <band:3>20m <mode:2>CW <qso_date:8>20240115 <time_on:4>1430 <eor>
        """

        let parser = ADIFParser()
        let records = try parser.parse(adif)

        #expect(records.count == 1)
        #expect(records[0].callsign == "W1AW")
    }

    @Test("Parse timestamp")
    func parseTimestamp() throws {
        let adif = "<call:4>W1AW <band:3>20m <mode:2>CW <qso_date:8>20240115 <time_on:4>1430 <eor>"

        let parser = ADIFParser()
        let records = try parser.parse(adif)

        #expect(records[0].timestamp != nil)

        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd HH:mm"
        formatter.timeZone = TimeZone(identifier: "UTC")

        let timestamp = try #require(records[0].timestamp)
        #expect(formatter.string(from: timestamp) == "2024-01-15 14:30")
    }

    @Test("Parse POTA fields")
    func parsePOTAFields() throws {
        let adif = """
        <call:4>W1AW <band:3>20m <mode:2>CW <qso_date:8>20240115 <time_on:4>1430 \
        <sig_info:6>K-1234 <my_gridsquare:6>FN31pr <eor>
        """

        let parser = ADIFParser()
        let records = try parser.parse(adif)

        #expect(records[0].sigInfo == "K-1234")
        #expect(records[0].myGridsquare == "FN31pr")
    }

    @Test("Parse my_sig_info")
    func parseMySigInfo() throws {
        // my_sig_info is YOUR park reference (activations), sig_info is THEIR park (hunter contacts)
        let adif = """
        <call:4>W1AW <band:3>20m <mode:2>CW <qso_date:8>20240115 <time_on:4>1430 \
        <my_sig_info:6>K-5678 <sig_info:6>K-1234 <eor>
        """

        let parser = ADIFParser()
        let records = try parser.parse(adif)

        #expect(records[0].mySigInfo == "K-5678") // Activation park
        #expect(records[0].sigInfo == "K-1234") // Hunter contact park
    }

    @Test("Skip invalid records")
    func skipInvalidRecords() throws {
        let adif = """
        <call:4>W1AW <band:3>20m <mode:2>CW <qso_date:8>20240115 <eor>
        <band:3>40m <mode:3>SSB <eor>
        <call:4>K3LR <band:3>40m <mode:3>SSB <eor>
        """

        let parser = ADIFParser()
        let records = try parser.parse(adif)

        // Second record missing callsign, should be skipped
        #expect(records.count == 2)
        #expect(records[0].callsign == "W1AW")
        #expect(records[1].callsign == "K3LR")
    }
}
